CREATE DATABASE [Biblioteca_G98]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Biblioteca_G98', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Biblioteca_G98.mdf' , SIZE = 5120KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Biblioteca_G98_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Biblioteca_G98_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
 WITH LEDGER = OFF
GO
ALTER DATABASE [Biblioteca_G98] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET ARITHABORT OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Biblioteca_G98] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Biblioteca_G98] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Biblioteca_G98] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Biblioteca_G98] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Biblioteca_G98] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Biblioteca_G98] SET  READ_WRITE 
GO
ALTER DATABASE [Biblioteca_G98] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Biblioteca_G98] SET  MULTI_USER 
GO
ALTER DATABASE [Biblioteca_G98] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Biblioteca_G98] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [Biblioteca_G98] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Biblioteca_G98]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Biblioteca_G98]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Biblioteca_G98] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
